set fallback := true

_default:
    @just --list

# build sd card image
build:
    nix build "$(git rev-parse --show-toplevel)#nixosConfigurations.aiagent.config.system.build.sdImage" --builders "$(just _builders)"
