# north -- main workstation (x86_64-linux)
#
# termfilechooser is a flake input passed in via specialArgs in flake.nix.
# It must be listed as a named argument here to be accessible.
{ config, lib, pkgs, termfilechooser, ... }:

{
  imports =
    [ # Generated by nixos-generate-config, describes the hardware (disks, NICs, etc.).
      ./hardware-configuration.nix
      ../../modules/desktop.nix
      ../../modules/core.nix
      ../../modules/syncthing-nixos.nix
      ../../modules/dev.nix
      ../../modules/nixvim.nix
      ../../modules/remote-desktop.nix
      ../../modules/infosec.nix
      ../../modules/tailscale.nix
      ../../modules/monitoring.nix
      ../../modules/users.nix
    ];

  # Option from modules/users.nix -- extends the charemma user's groups for this host.
  charemma.extraGroups = [ "networkmanager" "video" "audio" ];

  # Register aarch64-linux as an emulated system via QEMU binfmt_misc.
  # Allows running and building aarch64 binaries natively on x86_64.
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Separate EFI partition mounted at /boot/efi (common on dual-boot setups).
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  networking.hostName = "north";
  networking.networkmanager.enable = true;
  # Delegate DNS handling to systemd-resolved instead of NM writing /etc/resolv.conf
  # directly. Without this, NM and Tailscale race on resolv.conf after resume from
  # suspend/hibernate, leaving DNS broken until manual intervention.
  networking.networkmanager.dns = "systemd-resolved";

  time.timeZone = "Europe/Athens";
  i18n.defaultLocale = "en_US.UTF-8";

  services.pipewire = {
    enable = true;
    # ALSA support so legacy applications that use ALSA directly still work.
    alsa.enable = true;
    # PulseAudio compatibility layer so apps using the PulseAudio API work via PipeWire.
    pulse.enable = true;
  };

  programs.zsh.enable = true;

  # nix-ld provides a dynamic linker shim so pre-compiled binaries (e.g. downloaded executables)
  # can run on NixOS without patching their ELF interpreter.
  programs.nix-ld.enable = true;

  # Enable GPU drivers and OpenGL/Vulkan support.
  hardware.graphics.enable = true;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.trusted-users = [ "charemma" ];
  # Let remote builders pull dependencies from their own substituters
  # instead of having nix copy everything over SSH.
  nix.settings.builders-use-substitutes = true;
  # Allow packages with non-free licenses (e.g. burpsuite, obsidian).
  nixpkgs.config.allowUnfree = true;

  # Wake on LAN -- lets aiagent (on the same LAN) wake north remotely.
  # Find the interface name: ip link | grep -E '^[0-9]+: en'
  # Replace "enp6s0" below with the actual name, then: just north::rebuild
  # MAC: 10:7c:61:45:d8:99
  networking.interfaces."eno1".wakeOnLan.enable = true;

  # NFS client: mount aiagent's ~/code at /code.
  # x-systemd.automount defers the actual mount until first access and survives
  # aiagent being temporarily unreachable (soft + timeout prevent hard hangs).
  systemd.tmpfiles.rules = [ "d /code 0755 root root -" ];

  fileSystems."/code" = {
    device = "aiagent.tail48929d.ts.net:/code";
    fsType = "nfs4";
    options = [
      "_netdev"
      "noauto"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "soft"
      "timeo=30"
      "retrans=2"
    ];
  };

  system.stateVersion = "26.05";
}
