# north -- main workstation (x86_64-linux)
#
# termfilechooser is a flake input passed in via specialArgs in flake.nix.
# It must be listed as a named argument here to be accessible.
{ config, lib, pkgs, termfilechooser, ... }:

{
  imports =
    [ # Generated by nixos-generate-config, describes the hardware (disks, NICs, etc.).
      ./hardware-configuration.nix
      ../../modules/desktop.nix
      ../../modules/core.nix
      ../../modules/dev.nix
      ../../modules/remote-access.nix
      ../../modules/infosec.nix
      ../../modules/binary-cache.nix
      # Creates a network bridge for QEMU VMs (see module for details).
      ../../modules/vm-bridge.nix
      ../../modules/users.nix
    ];

  # Option from modules/users.nix -- extends the charemma user's groups for this host.
  charemma.extraGroups = [ "networkmanager" "video" "audio" ];

  # Register aarch64-linux as an emulated system via QEMU binfmt_misc.
  # Allows running and building aarch64 binaries natively on x86_64.
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Separate EFI partition mounted at /boot/efi (common on dual-boot setups).
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  networking.hostName = "north";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Athens";
  i18n.defaultLocale = "en_US.UTF-8";

  services.pipewire = {
    enable = true;
    # ALSA support so legacy applications that use ALSA directly still work.
    alsa.enable = true;
    # PulseAudio compatibility layer so apps using the PulseAudio API work via PipeWire.
    pulse.enable = true;
  };

  programs.zsh.enable = true;

  # nix-ld provides a dynamic linker shim so pre-compiled binaries (e.g. downloaded executables)
  # can run on NixOS without patching their ELF interpreter.
  programs.nix-ld.enable = true;

  # Enable GPU drivers and OpenGL/Vulkan support.
  hardware.graphics.enable = true;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.trusted-users = [ "charemma" ];
  # Allow packages with non-free licenses (e.g. burpsuite, obsidian).
  nixpkgs.config.allowUnfree = true;

  # Let remote builders pull dependencies from their own substituters (e.g. attic cache)
  # instead of having nix copy everything over SSH.
  nix.settings.builders-use-substitutes = true;

  system.stateVersion = "26.05";
}
