set fallback := true

_root := `git rev-parse --show-toplevel`

_default:
    @just --list

# build sd card image
build:
    nix build -o "{{ _root }}/results/rpi5" "{{ _root }}#nixosConfigurations.rpi5.config.system.build.sdImage" --builders "$(just _builders)"

# flash sd card image to device (usage: just rpi5::flash /dev/sdX)
flash device:
    zstdcat {{ _root }}/results/rpi5/sd-image/*.img.zst | sudo dd of={{ device }} bs=4M status=progress
    sync

# deploy config to running device over SSH
deploy:
    nixos-rebuild switch --flake "{{ _root }}#rpi5" --target-host charemma@rpi5 --use-remote-sudo
